import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    products,
    favoriteRecipes,
  ];
  late final Shape0 products = Shape0(
      source: i0.VersionedTable(
        entityName: 'products',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(barcode)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 favoriteRecipes = Shape1(
      source: i0.VersionedTable(
        entityName: 'favorite_recipes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get barcode =>
      columnsByName['barcode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brand =>
      columnsByName['brand']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imageUrl =>
      columnsByName['image_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categories =>
      columnsByName['categories']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ingredients =>
      columnsByName['ingredients']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get allergens =>
      columnsByName['allergens']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isFavorite =>
      columnsByName['is_favorite']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<double> get calories =>
      columnsByName['calories']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get protein =>
      columnsByName['protein']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fat =>
      columnsByName['fat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get carbs =>
      columnsByName['carbs']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get expirationDate =>
      columnsByName['expiration_date']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>('barcode', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('brand', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('image_url', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('quantity', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>('categories', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>('ingredients', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>('allergens', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_8(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_favorite', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_favorite" IN (0, 1))'),
        defaultValue: const Constant(false));
i1.GeneratedColumn<double> _column_9(String aliasedName) =>
    i1.GeneratedColumn<double>('calories', aliasedName, true,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_10(String aliasedName) =>
    i1.GeneratedColumn<double>('protein', aliasedName, true,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>('fat', aliasedName, true,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_12(String aliasedName) =>
    i1.GeneratedColumn<double>('carbs', aliasedName, true,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<DateTime> _column_13(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('expiration_date', aliasedName, true,
        type: i1.DriftSqlType.dateTime);

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get image =>
      columnsByName['image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get readyInMinutes =>
      columnsByName['ready_in_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get servings =>
      columnsByName['servings']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get summary =>
      columnsByName['summary']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get instructions =>
      columnsByName['instructions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceUrl =>
      columnsByName['source_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get extendedIngredientsJson =>
      columnsByName['extended_ingredients_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get analyzedInstructionsJson =>
      columnsByName['analyzed_instructions_json']!
          as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>('title', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>('image', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>('ready_in_minutes', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>('servings', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>('summary', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>('instructions', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>('source_url', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>('extended_ingredients_json', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>('analyzed_instructions_json', aliasedName, true,
        type: i1.DriftSqlType.string);
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from3To4: from3To4,
    ));
